# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: karendavila/bd
    command: mysqld --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      
